version: "3"

services:
  db:
    container_name: subsquid_db
    image: postgres:14
    # hostname: DBgoovBot
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: squid
    # command: ["postgres", "-c", "log_statement=all"]
    # volumes:
    #   - ./data_DB/db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    # networks:
    #   bridge_phalaTeamFR :
    #     ipv4_address: 127.0.0.10

  # squid-processor:
  #   image: squid-processor
  #   hostname: SqdProcGoovBot
  #   environment:
  #     DB_NAME: squid
  #     DB_PASS: squid
  #     DB_PORT: 23798
  #     PROCESSOR_PROMETHEUS_PORT: 3000
  #     GQL_PORT: 4350
  #     DB_HOST: 112.6.0.2
  #   depends_on:
  #   - db
  #   networks:
  #     bridge_phalaTeamFR :
  #       ipv4_address: 112.6.0.3

  # squid-graphql-server:
  #   image: graphql-server
  #   hostname: SqdGraphGoovBot
  #   ports:
  #   - "23798:4350"
  #   environment:
  #     DB_NAME: squid
  #     DB_PASS: squid
  #     DB_PORT: 23798
  #     PROCESSOR_PROMETHEUS_PORT: 3000
  #     GQL_PORT: 4350
  #     DB_HOST: 112.6.0.2
  #   depends_on:
  #   - db
  #   networks:
  #     bridge_phalaTeamFR :
  #       ipv4_address: 112.6.0.4


# networks:
#   bridge_phalaTeamFR:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 127.0.0.10/16
#           gateway: 127.0.0.1